language: d
sudo: false
dist: trusty

install:
    - git clone https://github.com/atilaneves/reggae.git
    - cd reggae
    - dub build
    - export PATH=$PWD/bin:$PATH
    - cd ..
    - dub fetch d2sqlite3 && dub build d2sqlite3 --config=all-included --compiler=$DC
    - if [ "$DC" == "ldc2" ]; then export DC=ldmd2; fi
    - reggae -b make --dc ${DC} --dflags -cov
    - if [ "$DC" == "ldmd2" ]; then export DC=ldc2; fi

os:
    - linux
      # TODO: macos shared DB libs.
      # - osx

d:
    - dmd-2.082.1 # 2018 Oct 10 / Add UDAs on function parameters.
    - dmd-2.081.2 # 2018 Aug 12 / Add expression-based contracts.
    - dmd-2.080.1 # 2018 Jun 7
    - dmd-2.079.1 # 2018 Apr 14
    - dmd-2.078.3 # 2018 Feb 15 / body->do
    - dmd-2.077.1 # 2017 Nov 29
    - dmd-2.076.1 # 2017 Oct 9
    - ldc-1.11.0 # 2.081.2
    - ldc-1.10.0 # 2.080.1
    - ldc-1.9.0 # 2.079.1
    - ldc-1.8.0 # 2.078.3
    - ldc-1.7.0 # 2.077.1
    - ldc-1.6.0 # 2.076.1

script:
    - make ut && ./ut

after_success:
    - bash <(curl -s https://codecov.io/bash)
